# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 08-15-2018
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 0,  car_type: "Liviano", km_max: 50000, km_min: 40000, month_max: 30, month_min: 24)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 1,  car_type: "Liviano", km_max: 50000, km_min: 40000, month_max: 30, month_min: 24)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 2,  car_type: "Liviano", km_max: 50000, km_min: 40000, month_max: 30, month_min: 24)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 3,  car_type: "Liviano", km_max: 50000, km_min: 40000, month_max: 30, month_min: 24)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 4,  car_type: "Liviano", km_max: 50000, km_min: 40000, month_max: 30, month_min: 24)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 5,  car_type: "Liviano", km_max: 45000, km_min: 38000, month_max: 26, month_min: 22)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 6,  car_type: "Liviano", km_max: 45000, km_min: 38000, month_max: 26, month_min: 22)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 7,  car_type: "Liviano", km_max: 45000, km_min: 38000, month_max: 26, month_min: 22)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 8,  car_type: "Liviano", km_max: 45000, km_min: 38000, month_max: 26, month_min: 22)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 9,  car_type: "Liviano", km_max: 45000, km_min: 38000, month_max: 26, month_min: 22)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 10, car_type: "Liviano", km_max: 40000, km_min: 35000, month_max: 24, month_min: 20)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 11, car_type: "Liviano", km_max: 40000, km_min: 35000, month_max: 24, month_min: 20)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 12, car_type: "Liviano", km_max: 40000, km_min: 35000, month_max: 24, month_min: 20)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 13, car_type: "Liviano", km_max: 40000, km_min: 35000, month_max: 24, month_min: 20)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 14, car_type: "Liviano", km_max: 40000, km_min: 35000, month_max: 24, month_min: 20)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 15, car_type: "Liviano", km_max: 35000, km_min: 30000, month_max: 22, month_min: 19)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 16, car_type: "Liviano", km_max: 35000, km_min: 30000, month_max: 22, month_min: 19)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 17, car_type: "Liviano", km_max: 35000, km_min: 30000, month_max: 22, month_min: 19)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 18, car_type: "Liviano", km_max: 35000, km_min: 30000, month_max: 22, month_min: 19)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 19, car_type: "Liviano", km_max: 35000, km_min: 30000, month_max: 22, month_min: 19)
  # Setting.create(maintenance_type: "Cambio de bandas", car_age: 20, car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 20, month_min: 18)

  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 0,  car_type: "Liviano", km_max: 6000, km_min: 5500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 1,  car_type: "Liviano", km_max: 6000, km_min: 5500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 2,  car_type: "Liviano", km_max: 6000, km_min: 5500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 3,  car_type: "Liviano", km_max: 6000, km_min: 5500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 4,  car_type: "Liviano", km_max: 6000, km_min: 5500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 5,  car_type: "Liviano", km_max: 5500, km_min: 5100, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 6,  car_type: "Liviano", km_max: 5500, km_min: 5100, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 7,  car_type: "Liviano", km_max: 5500, km_min: 5100, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 8,  car_type: "Liviano", km_max: 5500, km_min: 5100, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 9,  car_type: "Liviano", km_max: 5500, km_min: 5100, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 10, car_type: "Liviano", km_max: 5000, km_min: 4800, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 11, car_type: "Liviano", km_max: 5000, km_min: 4800, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 12, car_type: "Liviano", km_max: 5000, km_min: 4800, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 13, car_type: "Liviano", km_max: 5000, km_min: 4800, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 14, car_type: "Liviano", km_max: 5000, km_min: 4800, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 15, car_type: "Liviano", km_max: 4900, km_min: 4500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 16, car_type: "Liviano", km_max: 4900, km_min: 4500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 17, car_type: "Liviano", km_max: 4900, km_min: 4500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 18, car_type: "Liviano", km_max: 4900, km_min: 4500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 19, car_type: "Liviano", km_max: 4900, km_min: 4500, month_max: 3, month_min: 2)
  # Setting.create(maintenance_type: "Cambio de aceite y filtros", car_age: 20, car_type: "Liviano", km_max: 4500, km_min: 4000, month_max: 3, month_min: 2)

  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 0,  car_type: "Liviano", km_max: 22000, km_min: 20000, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 1,  car_type: "Liviano", km_max: 22000, km_min: 20000, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 2,  car_type: "Liviano", km_max: 22000, km_min: 20000, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 3,  car_type: "Liviano", km_max: 22000, km_min: 20000, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 4,  car_type: "Liviano", km_max: 22000, km_min: 20000, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 5,  car_type: "Liviano", km_max: 21000, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 6,  car_type: "Liviano", km_max: 21000, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 7,  car_type: "Liviano", km_max: 21000, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 8,  car_type: "Liviano", km_max: 21000, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 9,  car_type: "Liviano", km_max: 21000, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 10, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 11, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 12, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 13, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 14, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 15, car_type: "Liviano", km_max: 19000, km_min: 18000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 16, car_type: "Liviano", km_max: 19000, km_min: 18000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 17, car_type: "Liviano", km_max: 19000, km_min: 18000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 18, car_type: "Liviano", km_max: 19000, km_min: 18000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 19, car_type: "Liviano", km_max: 19000, km_min: 18000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de líquidos", car_age: 20, car_type: "Liviano", km_max: 18000, km_min: 15000, month_max: 10, month_min: 8)

  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 0,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 1,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 2,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 3,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 4,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 5,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 6,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 7,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 8,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 9,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 10, car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 6)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 11, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 12, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 13, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 14, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 15, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 16, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 17, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 18, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 19, car_type: "Liviano", km_max: 9000, km_min: 7000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Alineación y balanceo", car_age: 20, car_type: "Liviano", km_max: 7000, km_min: 6000, month_max: 5, month_min: 4)

  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 0,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 7, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 1,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 2,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 3,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 4,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 5,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 6,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 7,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 8,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 9,  car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 10, car_type: "Liviano", km_max: 10000, km_min: 9000, month_max: 6, month_min: 5)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 11, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 12, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 13, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 14, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 15, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 16, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 17, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 18, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 19, car_type: "Liviano", km_max: 9000, km_min: 8000, month_max: 5, month_min: 4)
  # Setting.create(maintenance_type: "Inspección de frenos", car_age: 20, car_type: "Liviano", km_max: 7000, km_min: 6000, month_max: 4, month_min: 3)

# 10-29-2018
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 0,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 1,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 2,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 3,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 4,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 5,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 6,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 7,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 8,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 9,  car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 10, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 11, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 12, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 13, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 14, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 15, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 16, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 17, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 18, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 19, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)
  # Setting.create(maintenance_type: "Presión neumáticos", car_age: 20, car_type: "Liviano", km_max: 250, km_min: 250, month_max: 1, month_min: 0)

  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 0,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 1,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 2,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 3,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 4,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 5,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 6,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 7,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 8,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 9,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 10, car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 11, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 12, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 13, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 14, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 15, car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 16, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 17, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 18, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 19, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Inspección de amortiguadores", car_age: 20, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)

  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 0,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 1,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 2,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 3,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 4,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 5,  car_type: "Liviano", km_max: 22000, km_min: 20500, month_max: 14, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 6,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 7,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 8,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 9,  car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 10, car_type: "Liviano", km_max: 21500, km_min: 20000, month_max: 13, month_min: 12)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 11, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 12, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 13, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 14, car_type: "Liviano", km_max: 21000, km_min: 19500, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 15, car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 12, month_min: 11)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 16, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 17, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 18, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 19, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)
  # Setting.create(maintenance_type: "Reemplazar plumas del parabrisas", car_age: 20, car_type: "Liviano", km_max: 20000, km_min: 19000, month_max: 11, month_min: 10)

  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 0,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 1,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 2,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 3,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 4,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 5,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 6,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 7,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 8,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 9,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 10, car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 11, car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 12, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 13, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 14, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 15, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 16, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 17, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 18, car_type: "Liviano", km_max: 50000, km_min: 49000, month_max: 59, month_min: 57)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 19, car_type: "Liviano", km_max: 50000, km_min: 49000, month_max: 59, month_min: 57)
  # Setting.create(maintenance_type: "Cambiar amortiguadores", car_age: 20, car_type: "Liviano", km_max: 50000, km_min: 49000, month_max: 59, month_min: 57)

  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 0,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 1,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 2,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 3,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 4,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 5,  car_type: "Liviano", km_max: 60000, km_min: 52000, month_max: 63, month_min: 60)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 6,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 7,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 8,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 9,  car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 10, car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 11, car_type: "Liviano", km_max: 55000, km_min: 51000, month_max: 61, month_min: 59)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 12, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 13, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 14, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 15, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 16, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 17, car_type: "Liviano", km_max: 51000, km_min: 50000, month_max: 60, month_min: 58)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 18, car_type: "Liviano", km_max: 50000, km_min: 49000, month_max: 59, month_min: 57)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 19, car_type: "Liviano", km_max: 50000, km_min: 49000, month_max: 59, month_min: 57)
  # Setting.create(maintenance_type: "Inspección del catalizador", car_age: 20, car_type: "Liviano", km_max: 50000, km_min: 49000, month_max: 59, month_min: 57)

# 11-07-2018
  Setting.create(maintenance_type: "ABC de Motor", car_age: 0,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 1,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 2,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 3,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 4,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 5,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 6,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 7,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 8,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 9,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 10, car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 11, car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 12, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 13, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 14, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 15, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 16, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 17, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 18, car_type: "Liviano", km_max: 19000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 19, car_type: "Liviano", km_max: 19000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "ABC de Motor", car_age: 20, car_type: "Liviano", km_max: 19000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)

  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 0,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 1,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 2,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 3,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 4,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 5,  car_type: "Liviano", km_max: 21000, km_min: 19000, month_max: 13, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 6,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 7,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 8,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 9,  car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 10, car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 11, car_type: "Liviano", km_max: 20000, km_min: 18000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 12, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 13, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 14, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 15, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 16, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 17, car_type: "Liviano", km_max: 20000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 18, car_type: "Liviano", km_max: 19000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 19, car_type: "Liviano", km_max: 19000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)
  Setting.create(maintenance_type: "Cambiar Aceite de Caja", car_age: 20, car_type: "Liviano", km_max: 19000, km_min: 17000, month_max: 12, month_min: 11, priority: 1)

  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 0,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 1,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 2,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 3,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 4,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 5,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 6,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 7,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 8,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 9,  car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 10, car_type: "Liviano", km_max: 30000, km_min: 28000, month_max: 18, month_min: 17, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 11, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 12, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 13, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 14, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 15, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 16, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 17, car_type: "Liviano", km_max: 28000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 18, car_type: "Liviano", km_max: 18000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 19, car_type: "Liviano", km_max: 18000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)
  Setting.create(maintenance_type: "Cambiar Filtro de Combustible", car_age: 20, car_type: "Liviano", km_max: 18000, km_min: 25000, month_max: 17, month_min: 15, priority: 1)

