class Car < ApplicationRecord
  belongs_to :owner
  has_many :maintenance_histories, dependent: :destroy
  # Multiple images with ActiveStorage
  has_many_attached :images, dependent: :destroy
  
  validates :plate, :brand, :model, :current_km, :car_type, :week_km, presence: true
  validates :insurance_company, :insurance_month, :insurance_year, presence: true, if: [Proc.new { |c| (c.insurance_company.present? || c.insurance_month.present? || c.insurance_year.present?) }]

  # KM actual estimado usando KM semanal
  def current_km_estimated
    # 1 KM semanal a KM por hora (168)
    # 2 Tiempo transcurrido con el paso de las horas
    self.current_km + ((self.week_km / 168.0) * (((Time.now - self.updated_at) / 1.hour).round)) rescue 0
  end

  def pending_maintenances
    self.maintenance_histories.where(status: "Pendiente")
  end

  # Class methods
  class << self
    def get_brands_list
      ["ACURA", "ALFA ROMEO", "ARCTIC CAT", "ASIA", "AUDI", "AUSTIN HEALEY", "BAW", "BMW", "BYD", "CADILLAC", "CHANA", "CHANGAN", "CHANGHE", "CHERY", "CHEVROLET", "CHRYSLER", "CITROEN", "DAEWOO", "DAIHATSU", "DATSUN", "DAYANG", "DFSK", "DODGE", "DONGFENG", "FAW", "FIAT", "FORD", "FOTON", "GEELY", "GMC", "GREAT WALL", "HONDA", "HUMMER", "HYUNDAI", "INFINITI", "INTERNATIONAL", "ISUZU", "JAC", "JAGUAR", "JEEP", "JINBEI", "JINBEY HAISE", "JMC", "KAWASAKI", "KIA", "KING LONG", "LADA", "LAND ROVER", "LEXUS", "LIFAN", "LOTUS", "MAHINDRA", "MASERATI", "MAZDA", "MERCEDES BENZ", "MG", "MINI", "MITSUBISHI", "NEW SUPER", "NISSAN", "OLDSMOBILE", "PEUGEOT", "PLYMOUTH", "POLARIS", "PONTIAC", "PORSCHE", "QMC", "RENAULT", "SAAB", "SAIC WULING", "SCION", "SEAT", "SKODA", "SOUEAST", "SSANGYONG", "SUBARU", "SUZUKI", "TALBOT", "TATA", "TIANYE", "TOYOTA", "TUNDRA", "VOLKSWAGEN", "VOLVO", "ZOTYE", "ZXAUTO"]
    end
    def get_models_list
      {"ACURA" => ["INTEGRA", "RDX"], 
        "ALFA ROMEO" => ["156", "147", "Giulia Super", "Spider"], 
        "ARCTIC CAT" => ["WILDCAT X LIMITED 1000"], 
        "ASIA" => ["TOPIC"], 
        "AUDI" => ["Q5", "A4", "Q7", "A4 1.8T", "A3", "A6", "Q3", "A4 2.0T", "A1", "100", "Q5 Hybrid", "80", "A4 1.4T", "A4 3.0 V6", "A5"], 
        "AUSTIN HEALEY" => ["MINI 1000"], 
        "BAW" => ["JEEP", "LEICHI"], 
        "BMW" => ["118 D", "318", "116i", "118i", "320", "520", "2002", "120i", "218i ACTIVE TOURER", "316i", "318i", "318ti", "320i", "323i", "325 ci", "325i", "328 i Cabriolet", "328ci", "328i", "330 ci", "330i", "335i", "335i m Sport", "428i", "520i", "523i", "525i", "528i", "530i", "535i", "540i", "550i", "640i", "732i", "740i", "745 i", "750i", "ACTIVE 5 HYBRID", "Active Hybrid 3", "Active Hybrid 7", "Alpina", "M 240i", "M3", "M4", "M5", "M6", "Serie 3", "serie5", "X1", "X3", "X3 2.5i", "X3 2.5SI", "X3 3.0i", "X3 3.0SI", "X3 Drive 28i", "X3 Xdrive 35i", "X5 3.0i", "X5 3.0L", "X5 3.0Si", "X5 4.4i", "X5 4.6is", "X5 4.8i", "X5 M", "X5 xDrive35i", "X6", "X6 Hibrido", "X6 M", "X6 xDRIVE 35i", "xDRIVE", "Z4", "Z4 M"], 
        "BYD" => ["BYD", "F3", "F5", "FLYER", "FO", "M6", "S6", "YUAN GLX LF"], 
        "CADILLAC" => ["CTS COUPE", "ESCALADE", "FLEETWOOD BROUGHAM"], 
        "CHANA" => ["PICKUP"], 
        "CHANGAN" => ["CS35 LUXURY", "PICKUP"],
        "CHANGHE" => ["CH6390", "CH6430T2", "COOLCAR", "FREEDOM SL", "MINI VAN", "MINIVAN PANEL", "MINIVAN SL", "SPLASH"], 
        "CHERY"=> ["A1 NICE", "CHERY VAN", "CITY VAN", "CROSS", "FULWIN", "FULWIN HB 1.5", "PRACTIVAN 11", "PRACTIVAN KARRY", "PRACTIVAN YO-YO", "Q", "Q22L", "QQ 613", "QQ3", "QQ311", "QQ6", "TIGGO", "TIGGO 2", "TIGGO 3", "TIGGO 5", "VAN PASAJEROS"],
        "CHEVROLET" => ["ALTO", "ANDINO", "APACHE", "ASKA", "AVEO EMOTION GT", "AVEO GT3", "AVEO GT5", "AVEO GTI", "BUIK", "C10", "C20", "C30", "CAMARO", "CAMARO RS", "CAMARO SS", "CAPRICE CLASSIC", "CAPTIVA LIMITED", "CK 10", "210", "ASTRA", "AVEO", "AVEO ACTIVO", "AVEO EMOTION", "AVEO EMOTION ADVANCE", "AVEO EMOTION GLS", "AVEO FAMILY", "BLAZER", "CAPTIVA", "CAPTIVA SPORT", "CAPTIVA SPORT 4X4", "CAPTIVA SPORT V6 3.0", "CARGO", "CARRY", "CAVALIER", "CHEVETTE", "CHEVYTAXI", "CHEVYVAN", "CHEYENNE", "CONDOR", "CORSA", "CORSA EVOLUTION", "CORSA PICK UP", "CORSA WIND", "CORVAIR", "CORVETEE Z06", "CRUZE", "D-MAX", "D-MAX  HIGH COUTRY", "D-MAX 4X2 CD", "D-MAX 4X2 CS", "D-MAX 4X4 CD", "D-MAX 4X4 CS", "D-MAX CD 3.5 V6", "D-MAX CRDI  3.0 CD 4X2  DIESEL", "D-MAX CRDI 3.0 4X2 AC", "D-MAX CRDI 3.0 CD 4X4", "D-MAX CRDI AC 3.0 CD 4X4 TM DIESEL", "D-MAX CRDI AC 3.0 CS 4X4 TM DIESEL", "D-MAX CRDI FULL AC 3.0 CD 4X4", "D-MAX DOHC 2.4", "D-MAX TD 2.5 CS 4X2 TM DIESEL", "D-MAX TM 3.0 4X4 DIESEL", "D-MAX XTREME 3.0 DIESEL CD 4X4", "EQUINOX", "ESTEEM", "FORSA 1", "FORSA 2", "FRR", "GEMINI", "GRAND BLAZER", "GRAND VITARA 3P", "GRAND VITARA 3P SPORT", "GRAND VITARA 5P", "GRAND VITARA SZ", "GRAND VITARA SZ 2.4", "GRAND VITARA SZ 2.4 4X4", "GRAND VITARA SZ 4X4", "GRAND VITARA SZ NEXT", "GRAND VITARA SZ NEXT 2.4 4X2", "GRAND VITARA SZ NEXT SPORT TM", "GRAND VITARA SZ V6", "GRAND VITARA XL7", "HHR", "IMPALA", "JIMNY", "LUV CD", "LUV CD DIESEL", "LUV CS", "LUV D-MAX", "LUV D-MAX 3.5L V6 CD GLS TM 4X", "LUV D-MAX CD OPTIMA", "LUV D-MAX TM 2.4 4X2", "LUV D-MAX TM 3.0 4X2 DIESEL", "LUV D-MAX TM 3.0 4X4 DIESEL CD", "LUV D-MAX V6 4X2 CD TA", "LUV DMAX CD", "LUV DMAX CD DIESEL", "LUV DMAX CD V6", "LUV DMAX CS", "LUV DMAX CS DIESEL", "LUV V6 CD", "LUV V6 CS", "MALIBU", "MINIBLAZER", "MONTE CARLO", "MONZA", "N200", "N300", "N300 MAX CARGO 1.2L TM AC", "NKR", "NOVA", "OMEGA", "OPALA", "OPTRA", "OPTRA ADVANCE", "OPTRA HATCHBACK", "OPTRA LIMITED", "ORLANDO", "PICK UP", "RODEO", "S10", "SAIL", "SAN REMO", "SCROSS", "SILVERADO", "SILVERADO HIBRIDO", "SILVERADO HIBRIDO 4X4", "SPARK", "SPARK GT", "SPARK LITE", "STYLE", "SUBURBAN", "SUPER CARRY", "SWIFT", "TAHOE", "TAHOE HÍBRIDO", "TRACKER", "TRAILBLAZER", "TRAILBLAZER EXTENDED", "TRAILBLAZER SS", "TROOPER 3P", "TROOPER 5P", "VAN G30 SPORT", "VECTRA", "VITARA 3P", "VITARA 5P", "VITARA SZ 2.4  NEXT", "VIVANT", "ZAFIRA"], 
        "CHRYSLER"=> ["ASPEN", "CARAVAN", "NEON", "PACIFICA", "PT CRUISER", "300"], 
        "CITROEN" => ["AIR CROSS", "BERLINGO", "BERLINGO MULTISPACE", "C-ELYSEE", "C2", "C3", "C3 SX", "C4", "C4 PICASSO", "C4 VTR", "C5", "DS3", "DS4", "JUMPER AMBULANCIA", "JUMPER III HDI", "PICASSO", "XANTIA", "XSARA"], 
        "DAEWOO" => ["CIELO", "ESPERO", "LANOS", "MATIZ", "NUBIRA", "RACER", "TACUMA", "TICO"], 
        "DAIHATSU" => ["APPLAUSE", "CHARNAN", "COURER", "CUORE", "DELTA V1 128L", "FEROZA", "GRAN MOVE", "LF 20", "LF 20 V", "SIRION", "TERIOS"], 
        "DATSUN" => ["1200", "120 Y", "1000", "1500", "1800"], 
        "DAYANG" => ["CHOK"], 
        "DFSK" => ["C37", "K07 II"], 
        "DODGE" => ["ASPEN", "CARAVAN", "CHARGER", "D100", "DAKOTA", "DART SPORT", "DURANGO", "GRAND CARAVAN SE", "GRAND CARAVAN SXT", "JOURNEY", "JOURNEY SE", "JOURNEY SXT", "NITRO", "RAM", "RAM 1500", "RAM 3500", "STEALTH", "STEEL TWIN"], 
        "DONGFENG" => ["C37", "CITY-VAN", "FUNVAN", "H30 CROSS AC 1.6 5P 4X2", "MINI TRUCK", "PRACTIVAN KARRY 11", "RICH", "S30", "ZNA"], 
        "FAW" => ["ACTIS V80 FULL", "R7", "CA6440", "CA1010", "D60"], 
        "FIAT" => ["127 SPORT", "500 ABARTH", "500X POP", "500X TREKKING PLUS", "FULLBACK", "125", "128", "132", "500", "750", "FIORINO", "FIORINO FIRE", "IDEA ADVENTURE", "IDEA HLX", "MILLE", "PALIO", "PALIO ADVENTURE", "PREMIO", "SIENA", "SPAZIO", "STILO", "STRADA", "TIPO", "UNO", "UNO FIRE", "UNO VIVACE", "UNO WAY", "WEEKEND"], 
        "FORD" => ["350", "A 31", "AEROSTAR", "BRONCO", "CLUB WAGON", "CONTOUR", "COUNTRY SQUIRE", "COURIER", "CROW VICTORIA", "E-350 CLUB WAGON", "ECONOLINE", "ECOSPORT", "ECOSPORT TITANIUM", "EDGE", "EDGE LIMITED", "ELITE", "ESCAPE", "ESCAPE HIBRIDO", "ESCORT", "EXPEDITION", "EXPEDITION EDDIE BAUER", "EXPLORER", "EXPLORER 3P", "EXPLORER 5P", "EXPLORER EDDIE BAUER", "EXPLORER LIMITED", "EXPLORER SPORT 4X4", "EXPLORER XLT", "F-150 FX4", "F-150 KING RANCH", "F-350 SUPER DUTY", "F-350 XLT", "F100", "F150", "F150 CS 4X4", "F150 DC 4X2", "F150 DC 4X4", "F150 LARIAT RC", "F150 MC 4X4", "F150 RAPTOR SVT", "F150 RC 4X2", "F150 SC 4X2", "F150 SC AC3.7 CD 4X2 TA", "F150 XL CS", "F150 XLT 4X4 CREW CAB", "F150 XLT CD", "F150 XLT LARIAT", "F250", "F350", "FAIRMONT", "FESTIVA", "FIESTA", "FIESTA POWER", "FOCUS", "FUERTE", "FUSION", "GRANADA", "LARIAT F-150", "LTD", "MUSTANG", "MUSTANG GT", "OTROS", "RANGER", "RANGER CD", "RANGER CS", "RAPTOR", "SPORT TRACK", "TAUNUS", "TAURUS", "TORINO", "TRANSIT CONNECT TITANIUM", "U50", "WINDSTAR"], 
        "FOTON"=> ["VIEW C2", "EUROPARD 904"], 
        "GEELY" => ["MK"], 
        "GMC" => ["SIERRA", "JIMMY", "TERRAIN", "YUKON HIBRIDO", "SIERRA HIBRIDO"], 
        "GREAT WALL"=> ["C30", "C30 CONFORT", "C30 FULL LUXURY", "FLORID", "H3", "H3 2.0", "H5", "H5 DIESEL", "H5 ELITE", "H5 FULL", "H5 LUXURY", "H5 SUPER FULL", "H5 TURBO", "H5 TURBO 4X2 AC", "H5 TURBO 4X4 AC", "H6 4X2 AC", "HAVAL H2", "HAVAL H3 4X2", "HAVAL H5", "HAVAL H6", "HAVAL H9", "HOVER", "HOVER H3 FULL", "HOVER H5 ELITE", "HOVER H5 FULL", "M4", "M4 LUXURY", "VOLEEX C30", "WINGLE", "WINGLE 3 4X2 CD", "WINGLE 3 4X2 CS", "WINGLE 3 4X4 CD", "WINGLE 3 4X4 CS", "WINGLE 4X2 DIESEL CD PICK UP", "WINGLE 4X2 DIESEL CS PICK UP", "WINGLE 4X2 GAS CD PICK UP", "WINGLE 4X2 GAS CS PICK UP", "WINGLE 4X4 DIESEL CD PICK UP", "WINGLE 5", "WINGLE 5 AC CD 4X2", "WINGLE 5 AC CD 4X4"], 
        "HONDA" => ["ACCORD", "ACURA", "CIVIC", "CIVIC EX SPORT", "CR-V", "CR-Z EX HYBRID FULL", "CR-Z HIBRIDO", "CRX", "FIT", "HRV", "INTEGRA", "ODISSEY", "PILOT", "PRELUDE", "TORNADO"], 
        "HUMMER" => ["H3", "H2"], 
        "HYUNDAI" => ["ACCENT", "ACCENT NEW", "ACCENT VERNA", "ATOS", "AZERA", "COUPE", "CRETA", "ELANTRA", "EXCEL", "GENESIS", "GETZ", "GRAN I10", "GRAND SANTA FE", "H1", "H100", "I10", "I30", "IONIQ HYBRID", "KONA SEL", "MATRIX", "NEW ELANTRA", "PONY", "S CUOPE LS", "SANTA FE 4X2", "SANTA FE 4X4", "SANTA FE DIESEL", "SANTA FE V6 3.5", "SONATA", "SONATA HYBRID", "STAREX", "TERRACAN 2.5", "TERRACAN 2.9", "TERRACAN V6 3.5", "TIBURÓN", "TUCSON", "TUCSON 4X4", "TUCSON DIESEL", "TUCSON IX", "TUCSON IX 2.0 4X4", "TUCSON TA", "TUCSON TL", "VELOSTER", "VERACRUZ", "VERACRUZ DIESEL", "VERNA"], 
        "INFINITI" => ["G35"], 
        "INTERNATIONAL" => ["PICK UP", "R110"], 
        "ISUZU" => ["TROOPER", "RODEO"], 
        "JAC" => ["A-CLASS", "A0", "HFC 1037 DKST", "HK6700K4", "S3", "T6"], 
        "JAGUAR" => ["XJR"], 
        "JEEP" => ["CHEROKEE", "CHEROKEE LAREDO", "CHEROKEE LIMITED", "CHEROKEE SPORT", "CJ-5", "CJ-6", "CJ-7", "COMPASS", "COMPASS LIMITED", "GRAND CHEROKEE", "GRAND CHEROKEE LAREDO", "GRAND CHEROKEE LIMITED", "GRAND CHEROKEE OVERLAND", "GRAND CHEROKEE SRT8", "GRAND WAGONEER", "LIBERTY", "MUD", "PATRIOT", "RENEGADE", "RENEGADE LATITUDE", "WAGONEER", "WILLYS", "WRANGLER", "WRANGLER RUBICON", "WRANGLER SAHARA", "WRANGLER SPORT", "WRANGLER UNLIMITED OSCAR MIKE", "WRANGLER UNLIMITED SAHARA", "WRANGLER UNLIMITED SPORT", "WRANGLER UNLIMITED SPORT RHD"], 
        "JINBEI" => ["VAN"], 
        "JINBEY HAISE" => ["VAN"], 
        "JMC" => ["LANDWIND X2", "CAMIO 3.5 TONELADAS", "JX1043DL2TM", "JX1090TR23 TM", "S350"], 
        "KAWASAKI" => ["MULE 600"], 
        "KIA" => ["CARENS", "CARENS LX7", "CARENS R", "CARNIVAL", "CERATO", "CERATO FORTE", "CERATO KOUP", "CERATO R", "GRAN PREGIO", "GRAND CARNIVAL", "NIRO HYBRIDO", "OPIRUS", "OPTIMA", "PICANTO", "PICANTO R", "PREGIO", "QUORIS", "RIO", "RIO R", "RIO STYLUS", "RIO XCITE", "RONDO", "SEDONA", "SORENTO", "SOUL", "SPECTRA", "SPORTAGE", "SPORTAGE ACTIVE", "SPORTAGE ACTIVE 4X4 DIESEL", "SPORTAGE ACTIVE V6 4X4", "SPORTAGE GT LINE AT", "SPORTAGE LX", "SPORTAGE R", "SPORTAGE R LX 2.0", "SPORTAGE WAGON", "SPORTAGE X LINE", "TOWNER"], 
        "KING LONG" => ["FURGONETA 17 PASAJEROS", "KINGO MINIVAN"], 
        "LADA" => ["112 SPORT", "KALINA", "SAMARA", "100", "110", "111", "112", "2106", "2107", "115 GL", "NIVA"], 
        "LAND ROVER" => ["DEFENDER 110", "DEFENDER 90", "DEFENDER 90 TD5", "DISCOVERY", "DISCOVERY III", "DISCOVERY IV", "FREELANDER", "FREELANDER LR2", "LR3", "RANGE ROVER", "RANGE ROVER AUTOBIOGRAPHY", "RANGE ROVER EVOQUE", "RANGE ROVER EVOQUE HSE", "RANGE ROVER SPORT", "RANGE ROVER VOGUE", "SANTANA", "SERIES III", "VELAR"], 
        "LEXUS" => ["CT 200H", "GS450H", "HS 250H PREMIUM", "HS250H", "IS 250", "LS 430", "LX 450", "RX 300", "RX 330", "RX 350", "RX 450 HIBRIDO"], 
        "LIFAN" => ["1300 ELITE", "LF6 430", "LF6420", "LF7 132", "LF7160", "LIFANVAN", "SEASION", "X50", "X60", "320", "520"], 
        "LOTUS" => ["EVORA 400", "ELISE SPORT 220", "EVORA SPORT-410", "EXIGE SPORT 380"], 
        "MAHINDRA" => ["PICK UP CS", "PICK UP CD"], 
        "MASERATI" => ["LEVANTE", "LEVANTE S", "GHIBLI"], 
        "MAZDA" => ["6 GT", "ACTION", "B2000", "2", "5", "626", "929", "1000", "ALLEGRO", "ALLEGRO ELITE", "B1600", "B200", "B2200 CD", "B2200 CS", "B2600 CD", "B2600 CS", "BT 50 OUTDOORS", "BT-50 4X4", "BT-50 4X4 DIESEL", "BT-50 CD 4X2", "BT-50 CD 4X2 DIESEL", "BT-50 CD 4X4", "BT-50 CD 4X4 DIESEL", "BT-50 CD ACTION 2.6", "BT-50 CD RAUDA 2.2", "BT-50 CS 2.2", "BT-50 CS 2.6", "BT-50 DIESEL", "BT-50 TSX 4X4", "CX-3", "CX-3 FULL", "CX-5", "CX-5 FULL", "CX-9", "CX7", "MATSURI", "MIATA", "MIATA MX 5", "MPV", "MX-5", "MX3", "MX6", "NEW 3", "RX 3", "RX 7", "RX8", "TRIBUTE", "3", "6", "323", "BT-50"], 
        "MERCEDES BENZ" => ["180K", "190E", "230E", "240 ELEGANCE", "250E", "280 SEL", "180", "200", "230.6", "E280", "250", "260E", "280C", "280E", "280SE", "320E", "350SE", "350SLC", "500 SEL", "500SEC", "A 200", "A180", "A45 AMG", "C200 CGI", "C220", "C280 4MATIC", "C280 SPORT", "C320 T", "C350", "C63 AMG", "CLC 350", "CLK 230 K", "CLS 500", "CLS 55 AMG", "CLS 550", "E200", "E220", "E550", "G63 AMG", "GLA 250 AMG LINE", "GLA 45 AMG", "GLE 43", "ML 320 AMG", "ML 350 AMG", "ML550", "S 350", "S320", "S400 L HIBRIDO", "SL500", "SPRINTER 313", "SPRINTER 315", "280", "280S", "300E", "C180", "C180 CGI", "C180 K", "C200", "C200 K", "C230", "C230 KOMPRESOR", "C230 V6", "C240", "C250", "C280", "C300", "C320", "CLA 180", "CLA 200", "CLA 250", "CLK320", "E230", "E240", "E300", "E320", "E350", "GL450", "GLA 180", "GLA 250", "GLA 250 AMG", "GLC 250", "GLC 250 COUPE", "GLE 400", "GLK350", "ML 320", "ML 350 4MATIC", "ML 350 SPECIAL EDITION", "ML 400", "ML 500 AMG", "ML 63 AMG", "ML350", "ML500", "S400 HIBRIDO", "S400 HYBRID AMG", "S500", "SLC 200", "SLK 350", "SPRINTER 413", "SPRINTER 515", "VANEO CDI"], 
        "MG" => ["B GT"], 
        "MINI" => ["AUSTIN 1000", "AUSTIN 1300", "AUSTIN MINI VAN", "AUSTIN MORRIS", "COOPER", "COOPER CABRIO", "COOPER COUNTRYMAN", "COOPER COUPE S", "JOHN COOPER WORKS", "ONE"], 
        "MITSUBISHI" => ["ASX", "ECLIPSE", "GALANT", "GALANT VR", "L200", "L300", "LANCER", "LANCER EVOLUTION 8", "LANCER EVOLUTION 9", "LANCER EVOLUTION X", "LANCER GT", "MONTERO 3P", "MONTERO 5P", "MONTERO BLISTER", "MONTERO IO", "MONTERO SPORT", "MONTERO SPORT DIESEL", "OUTLANDER", "SAPPORO", "SPACE WAGON", "SPORTERO L200", "SPORTERO L200 LIMITED", "SPORTERO L200 TRITON"], 
        "NEW SUPER" => ["KTH 6485"], 
        "NISSAN" => ["1000", "120Y", "300ZX", "370 Z", "ALTIMA", "1200", "ALMERA", "ALTIMA HYBRID", "ARMADA", "BLUEBIRD", "CX7", "FRONTIER", "FRONTIER NP300", "JUKE", "KICKS", "LEAF", "MARCH", "MÁXIMA", "MURANO", "MURANO 4X2 AT", "NAVARA", "NOTE", "NP300", "PATHFINDER", "PATHFINDER PLATINUM", "PATROL", "PATROL GRX 4X4", "PATROL GRX MT DIESEL", "PATROL RXG", "PICK UP", "PICK UP CD", "PRIMERA", "QASHQAI", "QUEST", "ROGUE", "SE SPORT 2.0 MT", "SENTRA", "SENTRA 2.0 MT", "SENTRA ADVANCE AT", "SENTRA ADVANCE MT", "SENTRA B15", "SENTRA B17", "SENTRA EXCLUSIVE", "SENTRA EXCLUSIVE XTRONIC CVT", "SENTRA SPORT", "TIIDA", "TIIDA ENTRY", "TITAN", "URVAN", "VERSA", "X TRAIL SENSE", "X-TRAIL", "X-TRAIL EXCLUSIVE", "XTERRA", "XTRAIL ADVANCE", "XTRAIL CLASSIC", "XTRAIL HYPERAIL", "XTRAIL XTREME", "XTRAIL XTREME HYPERAIL"], 
        "OLDSMOBILE" => ["CUTLASS", "TORONADO", "CUTLASS SUPREME"], 
        "PEUGEOT" => ["206 S16", "607", "5008", "206 X", "206 XS", "206 XT", "206CC", "207 1.6 PREMIUM HDI", "207 COMPACT", "207 PLUS", "207CC", "307 SW", "307 XS", "307 XSI", "307 XTP", "307CC", "308CC.", "407 COUPE", "407 SW", "BERLINA 206 CONFORT", "BERLINA 206 XR PREMIUM", "BERLINA 206 XRS CONFORT", "BERLINA 307 X-LINE", "BERLINA 407", "BERLINA XR", "PARTNER", "RCZ", "206", "207", "208", "301", "306", "307", "308", "405", "406", "407", "408", "505", "508", "605", "3008"], 
        "PLYMOUTH" => ["GRAND VOYAGER SE"], 
        "POLARIS" => ["RZR 1000", "RZR 1000XP", "RZR 800", "RZR 900", "RZR S 800", "RZR XP 4 900", "RZR XP 900"], 
        "PONTIAC" => ["GRAND PRIX", "LEMANS", "SOLSTICE"], 
        "PORSCHE" => ["911-TURBO", "BOXSTER", "CAYENNE", "CAYENNE S", "CAYENNE S HYBRID", "CAYENNE TURBO", "CAYMAN", "MACAN", "MACAN S", "PANAMERA S HYBRID"], 
        "QMC" => ["FINE"], 
        "RENAULT" => ["5", "CLIO", "CLIO DYNAMIQUE", "DUSTER 1.6", "DUSTER 2.0", "KANGOO", "KOLEOS", "LAGUNA", "LOGAN", "LOGAN DYNAMIQUE", "LOGAN EXPRESSION 1.6", "LOGAN FAMILIER", "MEGANE", "SANDERO", "SANDERO DYNAMIC", "SANDERO GT LINE", "SANDERO STEPWAY", "SCENIC", "SYMBOL", "TWINGO", "TWIZY"], 
        "SAAB" => "96", "SAIC WULING" => ["MINI VAN PASAJEROS", "PICK UP", "MINI VAN CARGA"], 
        "SCION" => ["FRS"], 
        "SEAT" => ["IBIZA"], 
        "SKODA" => ["FABIA", "FABIA 5A", "FABIA A5", "FABIA COMBI", "FABIA SPORT GTI", "FAVORIT", "FELICIA", "FELICIA GLX", "OCTAVIA", "OCTAVIA A5", "OCTAVIA A5 COMBI STATION WAGON", "OCTAVIA A7", "OCTAVIA RS", "PICK UP", "RAPID", "ROOMSTER", "ROOMSTER SCOUT", "SUPERB", "TOUR"], 
        "SOUEAST" => ["DX3", "DX7"], 
        "SSANGYONG" => ["ACTYON", "KORANDO", "KORANDO SPORT", "KYRON", "MUSSO", "MUSSO SPORT", "REXTON", "REXTON XVT"], 
        "SUBARU" => ["IMPREZA", "IMPREZA WRX STI", "BRZ", "IMPREZA WRX"], 
        "SUZUKI"=> ["BUGGY", "CHANGHE FREEDOM", "CHANGHE SPLASH", "FORSA 1", "FORSA 2", "GRAND VITARA 3P", "GRAND VITARA 5P", "GRAND VITARA SZ", "GRAND VITARA SZ 2.0 4X4", "GRAND VITARA SZ 2.4", "GRAND VITARA SZ 2.4 4X4", "GRAND VITARA SZ 2.7", "GRAND VITARA SZ V6", "HORMIGA", "JIMNY", "LJ 80", "S CROSS", "SAMURAI", "SAMURAI SJ", "SIDEKICK", "SJ 413", "SPLASH", "SUPER CARRY", "SWIFT", "SX4", "SZ NEXT SPORT"], 
        "TALBOT" => ["HORIZON"], 
        "TATA" => ["INDICA", "XENON", "ACE 483"], 
        "TIANYE" => ["ADMIRAL DC"], 
        "TOYOTA"=> ["4 RUNNER", "4 RUNNER LIMITED", "4 RUNNER SR5", "4RUNNER SR5 PREMIUM", "ACE", "AURIS", "C-HR", "CAMRY", "CAMRY HIBRIDO", "CELICA", "COROLLA 1.2", "COROLLA 1.6", "COROLLA 1.8", "COROLLA XRS", "CORONA", "CRESSIDA", "CROWN SUPER SALOON", "800", "CROWN", "EKT HILUX 4X2 CS", "FJ CRUISER", "FJ CRUISER TRD", "FORTUNER 2.7", "FORTUNER 4.0", "GT 86", "1000", "HIACE", "HIGHLANDER", "HIGHLANDER HIBRIDO", "HIGHLANDER LIMITED HIBRIDO", "HILUX CD 4X2", "HILUX CD 4X2 DIESEL", "HILUX CD 4X4", "HILUX CD 4X4 DIESEL", "HILUX CS 4X2", "HILUX CS 4X4", "HILUX CS 4X4 DIESEL", "HILUX SR AC CD", "HILUX SR5", "INNOVA", "JEEP STATION", "LAND CRUISER", "LAND CRUISER 100", "LAND CRUISER 200", "LAND CRUISER 4500 EFI", "LAND CRUISER FJ 80", "LAND CRUISER FJ40", "LAND CRUISER GX", "LAND CRUISER PICKUP", "LAND CRUISER PRADO VX", "MARK II", "MR2", "NEW FORTUNER", "NEW HILUX SR", "NEW RAV 4", "NEW RAV4 2.5", "NEW RAV4 AC 2.0 5P", "PRADO 3P", "PRADO 5P", "PRADO GRANDE", "PRIUS", "PRIUS C SPORT", "PRIUS HYBRIDO", "RAV 4", "RAV4 3P", "SCION", "SEQUOIA", "SEQUOIA PLATINIUM", "SIENNA", "STOUT", "STOUT II", "T 100", "TACOMA", "TERCEL", "TUNDRA", "TUNDRA 1794", "YARIS", "YARIS NITRO", "YARIS S", "YARIS SPORT"], 
        "TUNDRA" => ["RAPTOR 250"], 
        "VOLKSWAGEN" => ["405 MI16", "AMAROK", "AMAROK 4X4", "AMAROK TDI", "AMAROK TSI", "BORA", "BORA EXCLUSIVE", "BORA STYLE ACTIVE 2.5 4P", "BRASILIA", "CADDY", "CARAVELLE FULL", "CC", "CRAFTER", "CRAFTER 30", "CRAFTER 50", "CROSSFOX", "CROSSOVER", "ESCARABAJO", "FOX", "GOL", "GOL CONFORTLINE 1.8", "GOL POWER", "GOL SPORT", "GOLF", "GOLF CONFORTLINE", "GOLF CONFORTLINE 1.9 TDI", "GOLF GENERATION", "GOLF GTI", "GOLF MANHATAN", "GOLF7", "JETTA", "JETTA 1.8T", "JETTA EUROPA 2.0", "JETTA GLI", "JETTA TRENDLINE TA", "JETTA TRENDLINE TM", "KOMBI", "NEW BEETLE", "NEW JETTA", "PARATI", "PASSAT", "POINTER", "POLO", "POLO CLASSIC", "SAFARI", "SANTANA", "SAVEIRO", "SEMI SPORT", "SPACEFOX", "T5", "TIGUAN", "TOUAREG", "TOUAREG HIBRIDO", "TRANSPORTER", "VARIANT", "VENTO", "VENTO GLS", "VENTO VR6", "VOYAGE", "Z"], 
        "VOLVO" => ["240", "240GL", "740GL", "740T", "850 T5", "850GLT", "850T", "C 70", "940", "C30", "S40", "S40 T5", "S60 T5", "V40", "V40 1.6 TM", "V70", "XC60 T5 RDESIGN", "XC90 T6", "960", "S80", "850", "S60", "XC 90", "XC70"], 
        "ZOTYE" => ["JEEP", "NOMADA", "T600", "XS6400", "Z100", "Z300", "Z500"], 
        "ZXAUTO" => ["ADMIRAL", "GRAND TIGER"]}

    end
  end

end
